name: fusion_wallet
description: Android/iOS wallet for Minter.Network

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master
  dio: ^3.0.9
  url_launcher: ^5.4.5
  equatable: ^1.1.1
  flutter_cupertino_localizations: ^1.0.1
  page_transition: ^1.1.5
  progress_dialog: ^1.2.2
  google_fonts: ^1.0.0
  path_provider: ^1.6.7
  async: ^2.4.1
  flutter_spinkit: ^4.1.2+1
  flutter_platform_widgets: ^0.32.5
  flutter_staggered_animations: ^0.1.2
  bloc: ^4.0.0
  provider: ^4.0.5+1
  flutter_bloc: ^4.0.0
  rubber: ^0.4.0
  qr_flutter: ^3.2.0
  flutter_datetime_picker: ^1.3.8
  pin_input_text_field: ^3.0.1
  crypto: ^2.1.4
  flutter_svg: ^0.17.4
  local_auth: ^0.6.2+1
  meta: ^1.1.8
  fluttertoast: ^4.0.1
  flutter_secure_storage: ^3.3.3
  nanodart: ^1.0.0
  flare_flutter: ^2.0.3
  pointycastle: ^1.0.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  web_socket_channel: ^1.1.0

  # Platform-specific build info
  package_info: ^0.4.0+17

  # Device-specific info
  device_info: ^0.4.2+2

  # JSON Serialization
  json_annotation: ^3.0.1

  # Localization
  intl: ^0.16.1

  # BigDecimal alternative
  decimal: ^0.3.5

  # Logger
  logger: ^0.9.1

  # Native webview plugin
  flutter_webview_plugin: ^0.3.11

  # SQLite
  sqflite: ^1.3.0

  # Eventbus
  event_taxi: ^0.1.5

  # QR Codes

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

  # File picker
  file_picker: ^1.7.0

  # Deep link support
  #uni_links: ^0.2.0
  uni_links:
    git:
      url: https://github.com/CathalT/uni_links.git
      ref: nfc_android

  # HTTP client
  http: ^0.12.0+4

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^2.3.2

  # Push notifications
  firebase_messaging: ^6.0.13

  # Slidable list actions
  flutter_slidable: ^0.5.4

  # Lock helper
  synchronized: ^2.2.0
  modal_bottom_sheet: ^0.1.5

  # Service provider
  get_it: ^4.0.1
  shared_preferences: ^0.5.7
  # Root/Jailbreak detection
  root_checker:
    git:
      url: https://github.com/bbedward/root_checker.git
      ref: master

  # Validation utilities
  validators: ^2.0.0+1

  # Auto resize text widget
  auto_size_text: ^2.1.0
  settings_ui: ^0.2.0
  form_bloc: 0.14.0
  flutter_form_bloc: ^0.14.0
  random_string: ^2.0.1
# Avoid keyboard from overlapping text fields
  keyboard_avoider: ^0.1.2

dev_dependencies:
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  intl_translation: ^0.17.10
  flutter_launcher_icons: ^0.7.5
  hive_generator: ^0.7.0+2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"



flutter:


  uses-material-design: true



  assets:
    - assets/lang/en.json
    - assets/lang/ru.json



    - assets/images/backgrounds/bg_primary.png
    - assets/images/backgrounds/bg_greeting.png

    - assets/images/backgrounds/bg_primary.svg
    - assets/images/backgrounds/bg_greeting.svg
    - assets/images/backgrounds/bg_primary_light.svg

    - assets/images/icons/ic_qr.svg
    - assets/images/icons/ic_logo.svg
    - assets/images/icons/ic_accounts.svg
    - assets/images/icons/ic_backarrow.svg
    - assets/images/icons/ic_contacts.svg
    - assets/images/icons/ic_copypaste.svg
    - assets/images/icons/ic_default_settings.svg
    - assets/images/icons/ic_deletearrow.svg
    - assets/images/icons/ic_edit.svg
    - assets/images/icons/ic_exchange.svg
    - assets/images/icons/ic_faceid.svg
    - assets/images/icons/ic_folder.svg
    - assets/images/icons/ic_delete.svg
    - assets/images/icons/ic_hamburgermenu.svg
    - assets/images/icons/ic_history.svg
    - assets/images/icons/ic_infoicon.svg
    - assets/images/icons/ic_man.svg
    - assets/images/icons/ic_next.svg
    - assets/images/icons/ic_password.svg

    - assets/images/icons/ic_passwordellipse.svg

    - assets/images/icons/ic_pass_ellipse.svg

    - assets/images/icons/ic_qrcodescan.svg
    - assets/images/icons/ic_accounts.svg
    - assets/images/icons/ic_recoverpasswordicon.svg
    - assets/images/icons/ic_settings.svg
    - assets/images/icons/ic_shareicon.svg
    - assets/images/icons/ic_taskdone.svg
    - assets/images/icons/ic_toggleoff.svg
    - assets/images/icons/ic_toggleon.svg
    - assets/images/icons/ic_touch.svg
    - assets/images/icons/ic_touchid.svg
    - assets/images/icons/ic_add.svg
    - assets/images/icons/ic_withdraw.svg
    - assets/images/icons/ic_verified.svg
    - assets/images/icons/ic_bitcoin.svg
    - assets/images/icons/ic_copy.svg
    - assets/images/icons/ic_dollar.svg
    - assets/images/icons/ic_dollar.png

    - assets/images/icons/launcher.svg
