name: fusion_wallet
description: Android/iOS wallet for Minter.Network

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master
  dio: ^3.0.9
  url_launcher: ^5.4.2
  path: ^1.6.4
  equatable: ^1.1.1
  flutter_cupertino_localizations: ^1.0.1
  page_transition: ^1.1.5
  progress_dialog: ^1.2.2
  google_fonts: ^0.5.0+1
  path_provider: ^1.6.5
  async: ^2.4.1
  flutter_spinkit: ^4.1.2+1
  flutter_platform_widgets: ^0.32.5
  flutter_staggered_animations: ^0.1.2
  bloc: ^3.0.0
  provider: ^4.0.5
  flutter_bloc: ^3.2.0
  rubber: ^0.4.0
  qr_flutter: ^3.1.0
  flutter_datetime_picker: ^1.3.5
  pin_input_text_field: ^3.0.1
  crypto: ^2.1.4
  flutter_svg: ^0.17.4
  flutter_form_builder: ^3.8.3
  local_auth: ^0.6.1+3
  meta: ^1.1.8
  fluttertoast: ^4.0.1
  flutter_secure_storage: ^3.3.2
  nanodart: ^1.0.0
  flare_flutter: ^2.0.3
  pointycastle: ^1.0.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  web_socket_channel: ^1.1.0

  # Platform-specific build info
  package_info: ^0.4.0+16

  # Device-specific info
  device_info: ^0.4.2+1

  # JSON Serialization
  json_annotation: ^3.0.1

  # Localization
  intl: ^0.16.1

  # BigDecimal alternative
  decimal: ^0.3.5

  # Logger
  logger: ^0.8.3

  # Native webview plugin
  flutter_webview_plugin: ^0.3.11

  # SQLite
  sqflite: ^1.3.0

  # Eventbus
  event_taxi: ^0.1.5

  # QR Codes

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

  # File picker
  file_picker: ^1.6.2

  # Deep link support
  #uni_links: ^0.2.0
  uni_links:
    git:
      url: https://github.com/CathalT/uni_links.git
      ref: nfc_android

  # HTTP client
  http: ^0.12.0+4

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^2.3.2

  # Push notifications
  firebase_messaging: ^6.0.13

  # Slidable list actions
  flutter_slidable: ^0.5.4

  # Lock helper
  synchronized: ^2.2.0

  # Service provider
  get_it: ^4.0.1
  shared_preferences: ^0.5.6+3
  # Root/Jailbreak detection
  root_checker:
    git:
      url: https://github.com/bbedward/root_checker.git
      ref: master

  # Validation utilities
  validators: ^2.0.0+1

  # Auto resize text widget
  auto_size_text: ^2.1.0
  settings_ui: ^0.2.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: ^0.1.2
  manta_dart:
    git:
      url: https://github.com/bbedward/manta-dart.git
      ref: master


dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  intl: ^0.16.1
  intl_translation: ^0.17.10
  flutter_launcher_icons: ^0.7.4
  hive_generator: ^0.7.0+2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/lang/en.json
    - assets/lang/ru.json



    - assets/images/backgrounds/bg_primary.png
    - assets/images/backgrounds/bg_greeting.png

    - assets/images/backgrounds/bg_primary.svg
    - assets/images/backgrounds/bg_greeting.svg

    - assets/images/icons/ic_qr.svg
    - assets/images/icons/ic_logo.svg
    - assets/images/icons/ic_accounts.svg
    - assets/images/icons/ic_backarrow.svg
    - assets/images/icons/ic_contacts.svg
    - assets/images/icons/ic_copypaste.svg
    - assets/images/icons/ic_default_settings.svg
    - assets/images/icons/ic_deletearrow.svg
    - assets/images/icons/ic_edit.svg
    - assets/images/icons/ic_exchange.svg
    - assets/images/icons/ic_faceid.svg
    - assets/images/icons/ic_folder.svg
    - assets/images/icons/ic_hamburgermenu.svg
    - assets/images/icons/ic_history.svg
    - assets/images/icons/ic_infoicon.svg
    - assets/images/icons/ic_man.svg
    - assets/images/icons/ic_next.svg
    - assets/images/icons/ic_password.svg

    - assets/images/icons/ic_passwordellipse.svg

    - assets/images/icons/ic_pass_ellipse.svg

    - assets/images/icons/ic_qrcodescan.svg
    - assets/images/icons/ic_accounts.svg
    - assets/images/icons/ic_recoverpasswordicon.svg
    - assets/images/icons/ic_settings.svg
    - assets/images/icons/ic_shareicon.svg
    - assets/images/icons/ic_taskdone.svg
    - assets/images/icons/ic_toggleoff.svg
    - assets/images/icons/ic_toggleon.svg
    - assets/images/icons/ic_touch.svg
    - assets/images/icons/ic_touchid.svg
    - assets/images/icons/ic_add.svg
    - assets/images/icons/ic_withdraw.svg
    - assets/images/icons/ic_verified.svg
    - assets/images/icons/ic_bitcoin.svg
    - assets/images/icons/launcher.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
