name: fusion_wallet
description: Android/iOS wallet for Minter.Network

version: 1.0.0+10

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.4.5
  firebase_dynamic_links: ^0.5.3

  onesignal_flutter: ^2.6.0
  web3dart: ^1.2.3

  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  url_launcher: ^5.5.0
  equatable: ^1.2.3
  flutter_cupertino_localizations: ^1.0.1
  page_transition: ^1.1.6
  path_provider: ^1.6.11
  flutter_staggered_animations: ^0.1.2
  google_fonts: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  provider: ^4.3.0
  flutter_bloc: ^6.0.1
  qr_flutter: ^3.2.0
  flutter_datetime_picker: ^1.4.0
  pin_input_text_field: ^3.0.4
  crypto: ^2.1.5
  flutter_svg: ^0.18.0
  local_auth: ^0.6.2+3
  meta: ^1.1.8
  flutter_secure_storage: ^3.3.3
  nanodart: ^1.0.0
  pointycastle: ^1.0.2
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  package_info: ^0.4.1
  device_info: ^0.4.2+6
  json_annotation: ^3.0.1
  intl: ^0.16.1
  decimal: ^0.3.5
  logger: ^0.9.2
  alice: ^0.1.3
  share: ^0.6.4+3
  flutter_platform_widgets: ^0.60.1
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master
  modal_bottom_sheet: ^0.2.0+1
  get_it: ^4.0.4
  shared_preferences: ^0.5.8
  flutter_linkify: ^3.1.3
  root_checker:
    git:
      url: https://github.com/bbedward/root_checker.git
      ref: master
  validators: ^2.0.1
  auto_size_text: ^2.1.0
  form_bloc: ^0.19.1
  flutter_form_bloc: ^0.19.0
  random_string: ^2.1.0
  keyboard_avoider: ^0.1.2
  barcode_scan: ^3.0.1
  flutter_icons: ^1.1.0
  flash: ^1.3.1
  flutter_easyrefresh: ^2.1.5
  flutter_bounce: ^1.0.8
  styled_text: ^1.0.1+1

dependency_overrides:
  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1
  json_serializable: ^3.3.0
  intl_translation: ^0.17.10
  flutter_launcher_icons: ^0.7.5
  path: ^1.7.0
  hive_generator: ^0.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:

    - assets/anim/locker.json
    - assets/anim/locker2.json
    - assets/lang/en.json
    - assets/lang/ru.json

    - assets/images/icon.png

    - assets/images/backgrounds/bg_primary.png
    - assets/images/backgrounds/bg_greeting.png

    - assets/images/backgrounds/bg_primary.svg
    - assets/images/backgrounds/bg_greeting.svg
    - assets/images/backgrounds/bg_primary_light.svg

    - assets/images/icons/ic_qr.svg
    - assets/images/icons/ic_logo.svg
    - assets/images/icons/ic_accounts.svg
    - assets/images/icons/ic_backarrow.svg
    - assets/images/icons/ic_contacts.svg
    - assets/images/icons/ic_copypaste.svg
    - assets/images/icons/ic_default_settings.svg
    - assets/images/icons/ic_deletearrow.svg
    - assets/images/icons/ic_edit.svg
    - assets/images/icons/ic_exchange.svg
    - assets/images/icons/ic_faceid.svg
    - assets/images/icons/ic_folder.svg
    - assets/images/icons/ic_delete.svg
    - assets/images/icons/ic_hamburgermenu.svg
    - assets/images/icons/ic_history.svg
    - assets/images/icons/ic_infoicon.svg
    - assets/images/icons/ic_man.svg
    - assets/images/icons/ic_next.svg
    - assets/images/icons/ic_password.svg
    - assets/images/icons/ic_passwordellipse.svg
    - assets/images/icons/ic_pass_ellipse.svg
    - assets/images/icons/ic_qrcodescan.svg
    - assets/images/icons/ic_accounts.svg
    - assets/images/icons/ic_recoverpasswordicon.svg
    - assets/images/icons/ic_settings.svg
    - assets/images/icons/ic_shareicon.svg
    - assets/images/icons/ic_taskdone.svg
    - assets/images/icons/ic_toggleoff.svg
    - assets/images/icons/ic_toggleon.svg
    - assets/images/icons/ic_touch.svg
    - assets/images/icons/ic_touchid.svg
    - assets/images/icons/ic_add.svg
    - assets/images/icons/ic_withdraw.svg
    - assets/images/icons/ic_verified.svg
    - assets/images/icons/ic_bitcoin.svg
    - assets/images/icons/ic_copy.svg
    - assets/images/icons/ic_dollar.svg
    - assets/images/icons/ic_dollar.png
    - assets/images/icons/launcher.svg

